### ISSUE TITLE
Rename validation functions or add synonyms for JSKOS object types

### ISSUE THREAD

**Issue by stefandesu** [gbv/jskos-validate#2]
It should be possible to use the result of [jskos-tools' `getObjectType`](https://github.com/gbv/jskos-tools#guessObjectType) to validate an object of that type. So we should either rename the validation functions (so `validate.concept` => `validate.Concept`, `validate.scheme` => `validate.ConceptScheme`, etc.), or provide synonyms. Renaming would break functionality for all programs using this.

**Comment by nichtich** [comment]
With jskos-tools I added a second argument to `guessObjectType` to get the short name.
