### ISSUE TITLE
Avoid dependency on ajv

### ISSUE THREAD

**Issue by nichtich** [gbv/jskos-validate#5]
See https://github.com/epoberezkin/ajv-pack to minimize the size if used in a browser bundle

**Comment by stefandesu** [comment]
ajv-pack currently does not support recursive references which are used in JSKOS validation.

**Comment by nichtich** [comment]
So we need to work around it, e.g. create shallow schemas without recursive references and add code to step into nested structures for validating.

**Comment by stefandesu** [comment]
I'm only wondering why we should spend the effort at all. Right now, we're not using jskos-validate anywhere in the browser, and I'm not sure if we really need it back in Cocoda. Do you have any specific use case for it?
